apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Elastic Search Storage
  description: Elasticsearch storage plugin for Reekoh IoT Platform.
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - elastic
    - elasticsearch
  config:
    host:
      label: Host
      type: String
      maxLength: 1000
      required: true
      help: "Host of the ElasticSearch Server."
    port:
      label: Port
      type: Number
      required: false
      min: 1
      max: 56535
      help: "(Optional) Port of the ElasticSearch Server."
    protocol:
      label: Protocol
      type: String
      maxLength: 1000
      required: true
      enum:
        - http
        - https
      help: "Protocol in URL."
    user:
      label: User
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) User used for ElasticSearch authentication."
    password:
      label: Password
      type: Password
      maxLength: 1000
      required: false
      help: "(Optional) Password used for ElasticSearch authentication."
    apiVersion:
      label: API Version
      type: String
      maxLength: 1000
      required: false
      enum:
        - 1.0
        - 1.1
        - 1.2
        - 1.3
        - 1.4
        - 1.5
        - 1.6
        - 1.7
        - 2.0
        - 2.1
        - 2.2
      default: 2.1
      help: "(Optional) API version for ElasticSearch. Default: 2.1."
    index:
      label: Index
      type: String
      maxLength: 1000
      required: true
      help: "Name of the ElasticSearch Index to be used to store the data."
    type:
      label: Type
      type: String
      maxLength: 1000
      required: true
      help: "Name of the ElasticSearch Type to be used to store the data."
    idField:
      label: Id Field/Key
      type: String
      maxLength: 1000
      required: true
      help: "(Optional) If blank, assumed that id is auto-incremented otherwise, the value of this field is grabbed from the data and set as ID for the document."
    parentField:
      label: Parent Field/Key
      type: String
      maxLength: 1000
      required: true
      help: "(Optional) If blank, no parent will set otherwise, the value of this field is grabbed from the data and set as Parent for the document."

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??